# Site settings
title: Ben Showers
twitter_username: benshowers
name: Ben Showers

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://benshowers.com
 - title: LinkedIn
   url: https://uk.linkedin.com/in/ben-showers 

#Any buzzword skills you want to include
skills:
 - Digital Strategy and Leadership
 - Product and Project Management
 - Digital Programme Management
 - Agile
 - User Research

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://benshowers.com

#Work experience is required
roles:
 - title: Head of Digital
   start: March 2016
   end: Ongoing
   employer: The National Centre for Universities and Business
   description: Leading the development and implementation of the organisation’s digital and engagement strategy including NCUB’s digital channels and assets such as the website, social and media and brokerage platforms. Building a digital and agile culture alongside a portfolio of compelling products, services and content. 
 - title: Digital Transformation/Delivery Lead
   start: Dec 2014
   end: March 2016
   employer: Cabinet Office
   description: Led the delivery of multiple, complex digital/web projects across government. Working to deliver specific products or transformations as part of a multi-disciplinary, highly skilled agile team. Delivery of projects at pace while ensuring users (both internal and members of the public) are always at the heart of any change or new service.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: A range of functional and technical roles, primarily working on client sites in Financial Services.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#List of interesting Github repo/projects to include - optional


#Stackoverflow flair is optional

#Mobile apps section is optional


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
An experienced, delivery focused digital leader who is a passionate advocate for the power of digital and has 8 years’ experience successfully delivering large-scale, digital programmes and projects. Has led agile, cross discipline teams to develop products from initial exploration through to delivery and service. Has proven skills and experience in effective stakeholder management and communications, managing third party suppliers, project and programme management and digital strategy. 

