# Site settings
title: Ben Showers
twitter_username: benshowers
name: Ben Showers

# Build settings
markdown: kramdown

#User specific content
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
introInfo:

#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://benshowers.com
 - title: Twitter
   url: https://twitter.com/benshowers
 - title: LinkedIn
   url: https://uk.linkedin.com/in/ben-showers 

#Any buzzword skills you want to include
skills:
 - Digital Strategy and Leadership
 - Product and Project Management
 - Digital Programme Management
 - Agile
 - User Research
 - Digital Infrastructure
 - CRM
 

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://benshowers.com/feed/

#Work experience is required
roles:
 - title: Head of Digital
   start: March 2016
   end: Ongoing
   employer: The National Centre for Universities and Business
   description: Leading the development and implementation of the organisation’s digital and engagement strategy including NCUB’s digital channels and assets such as the website, social and media and brokerage platforms. Building a digital and agile culture alongside a portfolio of compelling products, services and content. 
 - title: Digital Transformation/Delivery Lead
   start: Dec 2014
   end: March 2016
   employer: Cabinet Office
   description: Led the delivery of multiple, complex digital/web projects across government. Working to deliver specific products or transformations as part of a multi-disciplinary, highly skilled agile team. Delivery of projects at pace while ensuring users (both internal and members of the public) are always at the heart of any change or new service.
 - title: Head of Digital Scholarship and Libraries
   start: 2013
   end: 2014
   employer: Jisc
   description: Provided senior leadership and strategy development within Jisc Futures directorate on developments in the digital scholarly process and digital content provision. Employing imaginative and creative approaches to exploit developments in the application of technology, user behaviour and analytics for the benefit of UK universities. 

#Education is required
education:
 - level: MA
   date: 2008
   subject: Information Studies
   school: University College London
 - level: MA (Distinction)
   date: 2001
   subject: Philosophy
   school: University of Sussex
   

#This section is optional (as is the image link below)

#Stackoverflow flair is optional

#Mobile apps section is optional


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
   <strong>Strategic Leadership and Management</strong>:Experience of both direct line management and matrix management of staff and suppliers. Significant experience in defining and developing strategic plans and objectives for both large-scale programmes as well as for specific, targeted digital interventions and products.  <br/><br/>
   <strong>User Engagement and Communication</strong>:In depth knowledge of various innovation/engagement models and approaches, including co-design, open innovation and the application of user research and UX. Experienced in working through traditional and social communication channels. A persuader with strong communication skills who is comfortable adapting styles for different audiences. <br/><br/>
   <strong>Project and Programme Management</strong>:Extensive practical experience of managing programme and projects of work both nationally and internationally, including collaborating with partners in the US as well as across Europe. Experienced in using various methodologies including agile and waterfall approaches. 
